// app/layout.tsx
import { Providers } from "./providers";
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { Button } from "@nextui-org/button";
import { Spinner } from "@nextui-org/spinner";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang="en" className='dark'>
			<body>
				<Providers>
					{children}
				</Providers>
			</body>
		</html>
	)
}
